services:
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: llama-cpp-server
    ports:
      - "8080:8080"
    environment:
      - LLAMA_ARG_HOST=0.0.0.0
    volumes:
      # Maps your local model folder to the container
      - /home/amitsarohi/llama_model:/models:rw
    command: ["-m","/models/Llama-3.2-3B-Instruct-Q4_K_M.gguf","-c","4096","--host", "0.0.0.0", "--port", "8080"]
    # Optional: Limits RAM usage like the -m flag in docker run
    deploy:
      resources:
        limits:
          memory: 4G
    restart: unless-stopped
